# -*- coding: utf-8 -*-
"""Questao1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P9tCJtZF1PkkRe2THSPbFMFmLUcFmpnt
"""

## QUESTÃO1

# Definir função que adquire um certo quesito para avaliar e a unidade de medida dele
def AvaliareEnviar(quesito,unidade_de_medida):

  # Abrir looping até que as condições do número sejam satisfeitas
  while True:
    numeroretorno=input(f'Insira {quesito} em {unidade_de_medida}. ')

    # Avaliar se número é realista tentando inferir que é um valor float
    try:
      float(numeroretorno)

      # Avaliar se número é positivo vendo se é maior que 0
      if float(numeroretorno)>0:
        return float(numeroretorno)
      else:
        print('Valor inválido. Tente novamente')

    except:
      print('Valor inválido. Tente novamente')

# Definir função que adquire a potencia e o tempo medio e calcula o consumo mensal em kWh
def calcular_consumo_mensal(pot, horas):

  # Aplicar fórmula na variável consmen
  consmen=pot*horas*30

  return consmen

# Utilizar a função definindo e avaliando o quesito potência
PotenciaEmKW=AvaliareEnviar('a potência do aparelho','kW')
# Utilizar a função definindo e avaliando o quesito tempo médio
TempoMedio=AvaliareEnviar('o tempo médio de uso diário','horas')

# Aplicando a função de cálculo na variável consumo_mensal
consumo_mensal = calcular_consumo_mensal(PotenciaEmKW,TempoMedio)

# Imprimindo resultado das contas e análise
print(f'\nCom base na potência {PotenciaEmKW} kW e \nno tempo médio de uso diário {TempoMedio} horas. \nO consumo mensal será {consumo_mensal:.2f} kWh.')