# -*- coding: utf-8 -*-
"""Questao2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sVZyu3GHUyhGUNvoMdG7W0SQB1VIcMbP
"""

## QUESTÃO2

# Variáveis de relatório
total_de_despesas=0
maior_valor_gasto=['',0]
custo_total_meta=0

# Categoria metas = metas ainda não estabelecidas, reais = descrição despesa x valor da despesa, gastos por categoria
categorias_metas={'1-Essencial':0, '2-Lazer':0, '3-Educação':0, '4-Saúde':0, '5-Segurança':0}
categorias_reais={'1-Essencial':[], '2-Lazer':[], '3-Educação':[], '4-Saúde':[], '5-Segurança':[]}
categorias_calculos={'1-Essencial':0, '2-Lazer':0, '3-Educação':0, '4-Saúde':0, '5-Segurança':0}

# Estabelecendo metas com looping
for categoria_meta in categorias_metas:
  meta_por_categoria=float(input(f'Defina uma meta financeira para a categoria {categoria_meta} em reais. '))
  categorias_metas[categoria_meta]=meta_por_categoria
  custo_total_meta+=meta_por_categoria

# Definir quantia de lançamentos4
quantia_lançamentos=int(input('Quantos lançamentos deseja inserir? (5 é o mínimo, pois precisamos de 1 em cada categoria para calcular a média)'))

# Estabelecendo valores reais com looping dentro das categorias
while quantia_lançamentos>0:

  # Acessar categoria, descrever despesa e colocar valor em despesa
  index_categoria_alvo=int(input('Qual categoria deseja inserir a despesa? (1, 2, 3, 4 ou 5) '))
  descricao_despesa=str(input('Insira a descrição da sua despesa. ')).capitalize().strip()
  valor_despesa=float(input('Insira o valor da sua despesa. '))

  # Calculando variáveis que serão usadas no relatório
  total_de_despesas+=valor_despesa

  # Acessar categoria tirando 1 unidade do index (começa em index 0) e entrando na lista
  list(categorias_reais.values())[index_categoria_alvo-1].append([descricao_despesa,valor_despesa])

  # Ir retirando lançamentos conforme dados para encerrar loop
  quantia_lançamentos-=1

# RELATÓRIO:

# Utilizando valores reais dados antes para gerar o relatório
print(f'O total de despesas no mês foi: R${total_de_despesas:.2f}')

# Calculando o gasto por categoria
for categoria,descricao_x_valores in categorias_reais.items():
  for lista in descricao_x_valores: # Acessar lista de descricao x valor no dicionario das categorias
    categorias_calculos[categoria]+=lista[1] # Somar valor mensal das listas no dicionario de calculos

# Printando custo mensal por categoria
for categoria,custo_mensal in categorias_calculos.items():
  print(f'O total de despesas no mês da categoria {categoria} foi: R${custo_mensal:.2f}')

# Calculando e printando custo médio mensal por categoria
for categoria,descricao_x_valores in categorias_reais.items():
  print(f'O valor médio de despesas no mês da categoria {categoria} foi: R${categorias_calculos[categoria]/len(descricao_x_valores):.2f}') # Dividindo o custo mensal de cada categoria pela quantia de despesas

# A categoria com maior valor gasto
for categoria,custo_mensal in categorias_calculos.items():

  # Defino variável de custo mensal e comparo conforme vou passando por cada categoria
  if custo_mensal>maior_valor_gasto[1]:
    maior_valor_gasto[1]=custo_mensal
    maior_valor_gasto[0]=categoria

# Printando o maior valor gasto
print(f'O maior valor gasto de despesas no mês da categoria {maior_valor_gasto[0]} foi: R${maior_valor_gasto[1]:.2f}')

# Printando análise comparativa
print(f'A comparação do custo total (real-meta) no mês foi R${total_de_despesas-custo_total_meta:.2f}')

# Printar cada dicionario que utilizei para organizar os valores
print('\n',categorias_metas) # Metas
print('\n',categorias_reais) # Valores reais do mês
print('\n',categorias_calculos) # Soma de custos por categoria