# -*- coding: utf-8 -*-
"""Questao4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7XZWxVmgH3OPl2Hb9vgTOvB3oQl03lv
"""

## QUESTÃO4

import time # Biblioteca para criar intervalo de tempo
import pandas as pd
from IPython.display import clear_output # Biblioteca para limpar terminal -> não sei se funciona no vscode

# Definir posições de cada peça baseado na matriz principal abaixo (montar tabuleiro)
def montarL(y,x):
  return [y-2,x],[y-1,x],[y,x],[y,x+1]

def montarQ(y,x):
  return [y,x],[y,x+1],[y-1,x],[y-1,x+1]

'''
exemplo:

x,y x+1,y
x,y+1 x+1,y+1

se eu quiser colocar uma peça X na matriz, eu posso definir uma posição variável
x,y para que eu aplique um valor nela e modifique posteriormente

'''

# Criar tabuleiro
def montarTabuleiro():
  return pd.DataFrame([
    ['⿴','⿴','⿴','⿴'],
    ['⿴','⿴','⿴','⿴'],
    ['⿴','⿴','⿴','⿴'],
    ['⿴','⿴','⿴','⿴'],
    ['⿴','⿴','⿴','⿴'],
    ['⿴','⿴','⿴','⿴'],
    ['⿴','⿴','⿴','⿴'],
    ['⿴','⿴','⿴','⿴'],
    ['⿴','⿴','⿴','⿴']])

# Definir limites de espaços que as peças podem ocupar
x_valores=range(0,4)
y_valores=range(0,9)

# Definindo pontuação
ponto='Infelizmente você não pontuou...'

# Criar matriz
matriz=montarTabuleiro()
print(matriz)

posicao_relativa=int(input('Insira um index (0, 1 ou 2) para inserir o L. '))

clear_output() # limpando terminal

# "Gravidade" da peça L com intervalo de tempo
for certa_coordenada_y in range(len(matriz)):

  if certa_coordenada_y < len(matriz): # Parando atualização da posição para printar a peça no final
    clear_output()
    matriz=montarTabuleiro()

  # Com base em uma certa coordenada y, a função varia fazendo a peça descer
  coordenadas_L=montarL(certa_coordenada_y,posicao_relativa)

  # Adquirindo as coordenadas constantes da peça
  for coordenada in coordenadas_L:
    cd1=coordenada[0]
    cd2=coordenada[1]
    if cd2 in x_valores and cd1 in y_valores: # se a peça estiver dentro do plano e o caractere que ela quer inserir estiver vazio '⿴', o programa preenche '𖣯'
      if matriz.loc[cd1,cd2]=='⿴':
        matriz.loc[cd1,cd2]='𖣯'
      else:
        break

  # Printando matriz com delay para dar efeito visual no terminal
  print(matriz)
  time.sleep(0.3)

limite_atingido=8

posicao_relativa_2=int(input('Insira um index (0, 1 ou 2) para inserir o QUADRADO. '))
clear_output()

for certa_coordenada_y_2 in range(len(matriz)):

  # Printar peça L já inserida
  coordenadas_L=montarL(8,posicao_relativa)

  # Adquirindo as coordenadas constantes da peça
  for coordenada in coordenadas_L:
    cd1=coordenada[0]
    cd2=coordenada[1]
    if cd2 in x_valores and cd1 in y_valores:
      if matriz.loc[cd1,cd2]=='⿴':
        matriz.loc[cd1,cd2]='𖣯'
      else:
        break

  # Printar peça QUADRADO
  coordenadas_Q=montarQ(certa_coordenada_y_2,posicao_relativa_2)

  # Adquirindo as coordenadas constantes da peça QUADRADO
  if limite_atingido!=0:
    for coordenada in coordenadas_Q:
      qd1=coordenada[0]
      qd2=coordenada[1]
      if qd2 in x_valores and qd1 in y_valores:
        if matriz.loc[qd1,qd2]=='⿴':
          matriz.loc[qd1,qd2]='𖣯'
        else:
          coordenada_fixa=certa_coordenada_y_2 # Fixo a coordenada onde o quadrado parou
          limite_atingido=0 # Digo ao sistema que o quadrado parou
          break

  # Se o quadrado estiver parado, ele printa de forma diferente a exata posição que o quadrado parou
  if limite_atingido==0:

    coordenadas_Q=montarQ(coordenada_fixa,posicao_relativa_2)

    for coordenada in coordenadas_Q:
      qd1=coordenada[0]
      qd2=coordenada[1]
      if qd2 in x_valores and qd1 in y_valores:
        if matriz.loc[qd1-1,qd2]=='⿴':
          matriz.loc[qd1-1,qd2]='𖣯'

  print(matriz)
  time.sleep(0.3)

  if certa_coordenada_y_2 < (len(matriz)-1): # Parando atualização da posição para printar a peça no final
    clear_output()
    matriz=montarTabuleiro()

# Checando se última camada está completa para pontuar
if (matriz.iloc[8] == '𖣯').all():
  matriz.loc[8,0]='⿴'
  matriz.loc[8,1]='⿴'
  matriz.loc[8,2]='⿴'
  matriz.loc[8,3]='⿴'
  ponto='Parabéns, você pontuou!'

# Finalizando
clear_output()
print(matriz,'\n',ponto)