# -*- coding: utf-8 -*-
"""Questao5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I4tyZfo2dvxRmNPE6KMd15e1jvRy0UYp
"""

## QUESTÃO5

'''
a) Qual foi o framework ou ferramenta tecnológica utilizada no seu projeto
final?
Explique brevemente para que ele serve e por que você (ou seu grupo)
escolheu usá-lo no desenvolvimento.

Usamos a Framework Flask implementada com OpenAI.
Usamos o Flask para criar um site e webapp que analisa links suspeitos.
Por meio de funções, iniciamos rotas que podemos configurar e comunicar
com outros arquivos HTML e fazer uma interface interativa que permite
a comunicação do usuário com o site de forma simples, por isso foi escolhida.
Usamos a OpenAI para importar a API do GPT-4.1 e utilizar ela para
classificações baseadas em web scrapping e APIs de análise. É uma API
muito completa, logo vital para usarmos.

b) Descreva uma funcionalidade concreta do seu projeto que foi construída
usando esse framework.
Explique com clareza o que essa funcionalidade faz, como ela foi
implementada e quais recursos específicos do framework foram aplicados
para torná-la possível.

Nosso projeto protege os usuários de tentativas de phishing e possíveis malwares, ocultos ou
expostos, em links que podem atacar o sistema operacional da pessoa sem que ela saiba.

Primeiro criamos rotas, isto é, caminhos dentro do site.
Moldamos cada rota em HTML para deixar a interface informativa.
Implementamos o método GET e POST em uma rota de análise de sites.
Basicamente esse método permite que o usuário insira um URL e esse URL vá para uma variável no arquivo python.
Avaliamos essa URL com a API da OpenAI e o output vem configurado em 4 tópicos de análise, devido ao promt que mandamos a API.
Utilizando a manipulação de strings do próprio python conseguimos dividir a análise numa lista para inserirmos no site.

c) Indique alguma funcionalidade ou recurso que você pesquisou, mas ainda
não conseguiu implementar.

Montamos, a parte, com uma biblioteca da google, um app que loga no gmail do usuário e analisa um email específico achado
com filtros que o próprio usuário coloca. A ferramenta de procura está pronta e a ferramenta de análise também, porém estão
separadas e estamos tentando juntá-las.
Além disso, precisamos tornar o aplicativo Web em um aplicativo mobile, o que além de ser muito complicado, ainda não achamos
uma saída sólida.

'''